README.md
kumulos/src/main/java/com/kumulos/android/AnalyticsBackgroundEventService.java
kumulos/src/main/java/com/kumulos/android/Kumulos.java
kumulos/src/main/java/com/kumulos/android/KumulosConfig.java

- Allow customising the base ACRA configuration used in Kumulos crash reporting
- In the background event sync service, limit the fields included in ACRA if the original process Kumulos was initialised in has been destroyed
To access the config builder methods in app projects, it is necessary for the ACRA library to be on the compiler's class path. Adding `compileOnly 'ch.acra:acra-http:5.1.3'` to the app's dependencies does the trick.

Expose ACRA config

---

kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

To allow seamless video playback for in-app messages, we don't want to require user interaction to play media.

Add media settings

---

kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

Bug: Message closed, dialog closed. Press back button --> crashes. 
Suppose because dialog is set to null, but object still exists for some time, so, when back button pressed listener calls close message. 
Fix:
1) remove listener
2) extra checks in `closeCurrentMessage`

Remove key listener when dialog dismissed

---

kumulos/src/main/java/com/kumulos/android/KumulosConfig.java
kumulos/src/main/java/com/kumulos/android/KumulosInApp.java

This avoids need to place the complex type in the Bundle for late initialisation
from onRunTask in background services.

Set in-app deep-link handler on KumulosInApp instead of in KumulosConfig

---

kumulos/src/main/java/com/kumulos/android/AnalyticsContract.java
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

When a button action for in-app messages includes opening a URL, the current activity is paused
which makes the ForegroundStateWatcher return null in presentMessagesToClient.
This in turn has the effect that the last message in the queue is not cleaning up the view when
the user navigates back to the app, and it appears the app is 'frozen' because the in-app overlay
is still on top of the screen.
The fix checks if the queue is empty in the public presentMessages routine, which is called when
the app resumes any activity, and then cleans up the view if there is nothing more to present.
- None
Prepare:
Release:

Clean up in-app overlay when app resumes after handling URL buttons

---

README.md
kumulos/src/main/java/com/kumulos/android/FirebaseMessageHandler.java
kumulos/src/main/java/com/kumulos/android/Kumulos.java
kumulos/src/main/java/com/kumulos/android/PushActionHandlerInterface.java
kumulos/src/main/java/com/kumulos/android/PushBroadcastReceiver.java
kumulos/src/main/java/com/kumulos/android/PushMessage.java

In order to support push action buttons need to read optional "k.buttons" key from data. For each button add action to the NotificationBuilder. When button clicked pending intent with `ACTION_BUTTON_CLICKED` is dispatched. This intent is caught by the same `PushBroadcastReceiver`, which in turns calls `pushActionHandler.handle()` if set by an app.
In order for it to work need to 
1) call `Kumulos.setPushActionHandler(new MyPushActionHandler());` (e.g. in App.onCreate)
2) add `<action android:name="com.kumulos.push.BUTTON_CLICKED" />` to PushBroadcastReceiver's intent filters in App's manifest
- None
Prepare:
Release:

Push action buttons

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppContract.java
kumulos/src/main/java/com/kumulos/android/KumulosInApp.java

Problem: user association results in an empty inbox
Solution:
1) do extra sync after user is associated
2) missing sync only explains empty inbox partly -- it would be read when the next sync happens. The 2nd problem was that messages only shown in inbox don't have ttl, but the sdk didn't handle null ttl properly. So, when reading all messages for the newly associated user if there is a single message without ttl, this would result in an Exception (logged, but no crash), so, other messages wouldn't be saved.
Add extra sync and guard against null
- None
Prepare:
Release:

Associating user results in an empty inbox

---

kumulos/src/main/java/com/kumulos/android/FirebaseMessageHandler.java
kumulos/src/main/java/com/kumulos/android/InAppRequestService.java
kumulos/src/main/java/com/kumulos/android/PushBroadcastReceiver.java
kumulos/src/main/java/com/kumulos/android/PushMessage.java
kumulos/src/main/java/com/kumulos/android/PushSubscriptionManager.java

1) show sentWhen
2) encode userIdentifier when doing in-app sync
3) display long text messages
4) Respect sound from payload. Users of the SDK should put sound file into `res/raw` and add file name without extension to the payload as in docs. On Android < O use `builder.setSound()`. On Android >= O we cannot use notification channels because cannot change sound after channel is created. So, instead change channel id to create a new channel (to deal with existing installs), disable channel sound, 'manually' play provided sound if user hasn't updated channel sound
5) update description of `channel.subscribe()`
Readme will be updated in the following MR
- None
Prepare:
Release:

Notification improvements: long-text, sound, time

---

README.md
kumulos/src/main/java/com/kumulos/android/PushBroadcastReceiver.java

1) Turn on vibration by default (with default vibration pattern)
2) Play default notification sound. 
**Notification sound rules are:**
1) When created channel does not have sound
2) Sdk cannot change channel sound, but user can. User cannot set sound to none/null, but can control silence via importance.
3) If channel sound set, play it (ignore custom sound / default sound)
4) If no channel sound, If channel importance <= LOW, leave without sounds
5) If no channel sound, if importance > LOW and no DnD: play default sound
6) If no channel sound, if importance > LOW and no DnD and custom sound: play custom sound
This changes previous behaviour: custom sound is not played if user set low importance (by selecting `Silent` vs `Alerting`). Notifications with importance > LOW play default sound …

Tweak notification sounds and vibration

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

Due to a bug in specific versions of Chromium, the onReceivedError handler can be invoked
spuriously for video resources.
Work around the issue by testing the specific failure conditions, and failing resource and
don't close the in-app dialog under those conditions.
See:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1023678
- https://bugs.chromium.org/p/chromium/issues/detail?id=1050635
- None
Prepare:
Release:

Fix for in-app messages containing videos randomly closing sometimes

---

README.md
kumulos/src/main/java/com/kumulos/android/Kumulos.java

When app is collapsed, the app process may get killed if phone is low on memory. If app is opened again, the latest activity is recreated. The activity gets same intent as the one that opened it initially. This means that if the app was opened by clicking a deep link, collapsing and expanding will result in the deep link / handler being processed again. 
Dont process deep links when activity recreated
Integration should be updated to 
```language-java
@Override
protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
Kumulos.seeIntent(this, getIntent(), savedInstanceState);
}
```
- None
Prepare:
Release:

Don't process deep links when activity recreated

---

README.md
kumulos/src/main/java/com/kumulos/android/Kumulos.java
kumulos/src/main/java/com/kumulos/android/PushBroadcastReceiver.java

Send 'k.message.dismissed' event when push notification dismissed. Same way as we handle notification opens
- None
Prepare:
Release:

Push Notification dismissed event 

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

`spinner.setVisibility(...)` fails with a NullPointerException. Spinner is stored as a static variable, which could have been garbage collected. Add null checks
- None
Prepare:
Release:

Guard rare in-app NullPointerException

---

README.md
kumulos/src/main/java/com/kumulos/android/AnalyticsContract.java
kumulos/src/main/java/com/kumulos/android/InAppContract.java
kumulos/src/main/java/com/kumulos/android/InAppDbHelper.java
kumulos/src/main/java/com/kumulos/android/InAppInboxItem.java
kumulos/src/main/java/com/kumulos/android/InAppMessage.java
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java
kumulos/src/main/java/com/kumulos/android/InAppMessageService.java
kumulos/src/main/java/com/kumulos/android/InAppSaveResult.java
kumulos/src/main/java/com/kumulos/android/KumulosInApp.java

New message property 'read'. The meaning of ‘message read’ is “User has seen the message, but not necessarily opened it”. Mark message as read when
1) message opened
2) inbox item deleted
3) Inbox item explicitly marked by user as read. For this expose 2 new public methods: `boolean markAsRead(Context context, InAppInboxItem item)` and `boolean markAllInboxItemsAsRead(Context context)`. Methods return true if all updates succeeded.
Additionally,
1) Consistent sort order of inbox items. sentAt DESC, updatedAt DESC, inAppId DESC. When presenting sorting fields same, but ASC
2) limit maximal amount of stored inApps to 50. Even if inbox is set to always, 51st message is going to be deleted (51st is the oldest).
3) Clear push tickle whenever inApp is deleted. We used to do this when message is …

In-app: mark as read

---

README.md
kumulos/src/main/java/com/kumulos/android/FirebaseMessageHandler.java
kumulos/src/main/java/com/kumulos/android/HmsMessageHandler.java
kumulos/src/main/java/com/kumulos/android/InAppContract.java
kumulos/src/main/java/com/kumulos/android/InAppDbHelper.java
kumulos/src/main/java/com/kumulos/android/InAppInboxItem.java
kumulos/src/main/java/com/kumulos/android/InAppInboxSummary.java
kumulos/src/main/java/com/kumulos/android/InAppInboxSummaryInfo.java
kumulos/src/main/java/com/kumulos/android/InAppMessage.java
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java
kumulos/src/main/java/com/kumulos/android/InAppMessageService.java
kumulos/src/main/java/com/kumulos/android/InAppSaveResult.java
kumulos/src/main/java/com/kumulos/android/KumulosInApp.java
kumulos/src/main/java/com/kumulos/android/PushMessage.java

1) `KumulosInApp.setOnInboxUpdated(() -> { });`. Callback runs every time there are changes relevant for inbox presentation. These are: 
- markRead
- markAllRead
- messageOpened (for this to work properly need to add `readAt` and `inbox` to every message in presentation queue)
- deleteInboxMessage
- sync
- eviction
The callback is run on UI thread. It is a responsibility of users to make sure `getInboxItems` (which is sync) they might wish to run afterwards is not blocking UI. 
Edge cases:
- inbox message drops out of availability window. It stays in inbox until evicted with next sync. This is very unlikely and badge and inbox both lag and then both get updated. If try to open such message get result EXPIRED as before
-  If we manually set inbox to null in db (e.g. customer request), …

In-app inbox extensions (updated hook, new fields, summary method)

---

README.md
kumulos/build.gradle

Crashes due to deprecation of methods used by okhttp
- None
Prepare:
Release:

Okhttp issues on android 11

---

README.md
kumulos/build.gradle

Cannot raise okhttp version without bumping android minSdk
- None
Prepare:
Release:

Revert okhttp to 3.12.x

---

README.md
kumulos/src/main/java/com/kumulos/android/DeferredDeepLinkHelper.java
kumulos/src/main/java/com/kumulos/android/HttpUtils.java

If deep link is opened by clicking a banner (WebSDK) extra query parameter is present on the copied URL. Pass it to API when reading deep link in order to track conversion.
- None
Prepare:
Release:

Pass webInstallId query parameter when reading deep link

---

kumulos/src/main/java/com/kumulos/android/AnalyticsContract.java
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

Fixes of very rare bugs:
1) dialog reference is null, even though checked before. 
```
Caused by java.lang.NullPointerException Attempt to invoke virtual method 'void android.app.Dialog.setOnKeyListener(android.content.DialogInterface$OnKeyListener)' on a null object reference
com.kumulos.android.InAppMessagePresenter.closeDialog (InAppMessagePresenter.java:347)
```
Clarity with threads in InAppMessagePresenter, add annotations. Run most functions on UIThread (as before) and make sure dialog is always closed on UI thread -- different threads setting it to null was the reason for the exception.
2) Index out of bounds exception, even though shouldn't be
```
Fatal Exception: java.lang.IndexOutOfBoundsException
Index: 0, Size: 0
java.util.ArrayList.get (ArrayList.java:437) …
```

Bugfixes for InAppMessagePresenter

---

README.md
kumulos/build.gradle
kumulos/src/main/java/com/kumulos/android/AnalyticsContract.java
kumulos/src/main/java/com/kumulos/android/ImplementationUtil.java
kumulos/src/main/java/com/kumulos/android/InAppContract.java
kumulos/src/main/java/com/kumulos/android/InAppInboxItem.java
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java
kumulos/src/main/java/com/kumulos/android/KumulosConfig.java
kumulos/src/main/java/com/kumulos/android/KumulosInApp.java
kumulos/src/main/java/com/kumulos/android/MediaHelper.java
kumulos/src/main/java/com/kumulos/android/PushBroadcastReceiver.java
kumulos/src/main/java/com/kumulos/android/PushRegistration.java

1) Drop session timeout to 23 seconds to match ios
2) Minor tweaks to annotations missed in inbox enhancements PR
3) Similarly to ObjC expose imageUrl on inbox items. For this add 2 methods: `public @Nullable URL getImageUrl(int width)` and `public @Nullable URL getImageUrl()`. Default width 300px
4) update targetSdk and compileSdk versions to 30. No [changes](https://developer.android.com/about/versions/11/behavior-changes-11) affect us.
5) version range for FirebaseMessaging [19.0.0, 22.99.99]. 19.0.0 is the 1st version supporting androidx. 22.0.0 is currently latest version of FM. Token retrieval/deletion API changed along the way, so, support 2 API versions. 
Range [19.0.0, 22.99.99] means that:
- If there is only 1 dependency on FM, latest version from the range is selected. 
- If …

SDK parity and inbox image APIs

---

kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

When the in-app message queue is empty, call the destroy method on the WebView as part of teardown
to ensure any managed resources the WebView has created are released cleanly.
https://developer.android.com/reference/android/webkit/WebView#destroy()
Format InAppMessagePresenter.
- None
Prepare:
Release:

Call destroy() on in-app WebView to fully clean up resources

---

README.md
kumulos/build.gradle

Range version checking does not work correctly when the Google Services gradle plugin is applied to consumer
app projects. This seems to be a bug/limitation in the Google Services gradle plugin logic.
This results in an error that can only be resolved by disabling version checking, which defeats the purpose
of supporting ranges of compatible versions of the FCM library.
As the Firebase libraries are moving towards Bill of Materials (BoM) specifications for dependency versioning,
revert our previous change in favour of supporting BoM more explicitly in an upcoming release.
See #60 for context on our addition of the version range for FCM.
Note this SDK still supports FCM versions 19 - 22 at runtime if resolution is different in the consumer project.
- None
Prepare: …

Revert specification of FCM library dependency as a range

---

README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
kumulos/build.gradle

Let SDK consumers set firebase messaging version they want. Suggested way is BoM -- consumers would need to add following lines to app-level build.gradle.
```
implementation platform('com.google.firebase:firebase-bom:28.2.0')
implementation 'com.google.firebase:firebase-messaging'
```
We support APIs in FM range [19, 22.99.99] which corresponds to BoM versions [20.0.0, 28.2.0]
Consumers have to add additional Firebase Messaging dependencies, or application would crash at runtime / push won't work
Prepare:
Release:

Use Firebase BoM

---

README.md
kumulos/src/main/java/com/kumulos/android/PushBroadcastReceiver.java
kumulos/src/main/java/com/kumulos/android/PushMessage.java

The Kumulos push API now supports the mutually exclusive keys 
- notificationType: Hint to the SDK whether a notification should default to the tray or a banner (priority default or max respectively), this is automatic and handled between the Kumulos push pipeline and the SDK.
- notificationChannel: If the app developer has setup specific channels for content then setting this key will forward it to the end consumer and is readable on the PushMessage object.
- None
Prepare:
Release:

Add Banner type push notifications and support selection of custom notification channels

---

README.md
kumulos/src/main/java/com/kumulos/android/PushBroadcastReceiver.java

If loading notification picture takes long (probably at least over 30 seconds), BroadcastReceiver hits background execution time limit and system considers the app non-responsive. Slow loading may be due to connection or the pic being resized to huge dimensions.
1) Add 24s timeout for read, 6s timeout for connection
2) if picture failed loading still show notification without the picture
- None
Prepare:
Release:

Fix ANR when loading push media over slow/unstable connections

---

README.md
kumulos/src/main/AndroidManifest.xml

Due to package visibility level changes, appst declare which queries for intents they plan to issue to the system.
Declare `ACTION_VIEW` queries for both `http://` and `https://` schemes.
- None
Prepare:
Release:
Post Release:

Fix in-app buttons launching URLs on apps targeting API level 30+

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppContract.java
kumulos/src/main/java/com/kumulos/android/InAppDeepLinkHandlerInterface.java
kumulos/src/main/java/com/kumulos/android/InAppJavaScriptInterface.java
kumulos/src/main/java/com/kumulos/android/InAppMessage.java
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java
kumulos/src/main/java/com/kumulos/android/InAppMessageService.java

Breaking change:
- `InAppDeepLinkHandlerInterface#handle(Context,JSONObject)` is now
`InAppDeepLinkHandlerInterface#handle(Context,InAppButtonPress)`
The `InAppButtonPress` model contains the original `JSONObject` in the
`deepLinkData` field, and additionally offers the in-app message's ID and
(optional) data field.
Changes throughout support selecting the data field from the database
during presentation / inbox operations to ensure it is available to
the button handler.
Changes to threading were introduced to allow access to the message presentation queue from the button handler. All button actions have been regression tested.
- `InAppDeepLinkHandlerInterface#handle(Context,JSONObject)` is now
`InAppDeepLinkHandlerInterface#handle(Context,InAppButtonPress)`
Prepare: …

Refactor InAppDeepLinkHandlerInterface to expose in-app message data

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java

In rare cases, the in-app renderer spinner could become stuck on the
screen.
This could happen due to failed network requests for critical assets
(HTML,CSS,JS from iar.app.delivery).
Occasionally on some devices it seems the WebView's cache can become
inconsistent and end up with a cached index.html requesting old CSS/JS
asset files.
These old asset requests result in 404s from the CDN.  In turn, the load
of the renderer never completes and the READY message is not received by
the host.
To address this, the following changes have been made:
- Change WebView cache strategy to LOAD_DEFAULT instead of
LOAD_CACHE_ELSE_NETWORK (this means that cached assets will expire
based on server cache headers rather than keep being used -- limit the
window of exposure for stale HTML/CSS/JS)
- Implement …

Fix rare edge case leading to infinite in-app spinner

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppJavaScriptInterface.java
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java
kumulos/src/main/res/layout/kumulos_dialog_view.xml

Fix cases where in-app spinner could be shown incorrectly:
- Prevent stale reads / races if view was cleaned up on main thread but guard executed on JS bridge thread
- Prefix layout resource IDs
- Cancel current in-app presentation queue when handling a 'terminating' button actions
The issue was most likely to present during in-app deep link navigation, and depending on how deep link handling was implemented.
- None
Prepare:
Release:
Post Release:

In-app spinner fixes

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppMessagePresenter.java
kumulos/src/main/java/com/kumulos/android/InAppMessageService.java

Fix an `IndexOutOfBoundsException` caused by JS thread messages trying to manipulate an empty message queue.
Although queue operations are all on the main thread, the sequencing can be out of order due to JS thread messages arriving after the presentatino has been cancelled.
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.get(ArrayList.java:437)
at com.kumulos.android.InAppMessagePresenter.lambda$messageOpened$2(InAppMessagePresenter.java:280)
at com.kumulos.android.-$$Lambda$InAppMessagePresenter$7cQQlEZ2DbLUZk4x4fKQPfOlJ3U.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at …
```

Fix IndexOutOfBoundsException on messageQueue operations

---

kumulos/src/main/java/com/kumulos/android/InAppJavaScriptInterface.java

If a button action from an in-app message specifies data for its
conversion event, pass this data through to the tracked event.
Data will be pre-merged server-side with reporting_meta and user_meta of
the particular message.
- None
Prepare:
~~Bump versions in:~~
~~Release:~~
Post Release:

Track event properties with in-app button conversion events

---

README.md
kumulos/src/main/java/com/kumulos/android/InAppMessageView.java

`getRootWindowInsets()` returns null when view is detached. Add null check to prevent NullPointerException. Detached view usually means activity is destroyed. 
- None
Prepare:
Release:
Post Release:

Dont set insets when view detached

---

README.md
kumulos/src/main/java/com/kumulos/android/DeferredDeepLinkHelper.java

Trying to read score when status is CLASSIFICATION_NOT_PERFORMED (This may be the case if the clip does not contain text in its first item, or if the text is too long) or CLASSIFICATION_NOT_COMPLETE (This will be always be the case if the clip has not been copied to clipboard, or if there is no associated clip.) will result in IllegalArgumentException
- None
Prepare:
Release:
Post Release:

Android 12 bugfix: Check classification status before reading score
